# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/bodmer.d/Downloads/pdatapath_lab5.xdc

# IP: ip/data_memory/data_memory.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==data_memory || ORIG_REF_NAME==data_memory} -quiet] -quiet
